version: "3.8"

services:
  mysql:
    container_name: mysql
    hostname: nysql
    image: mysql:8.4.2
    env_file:
      - .env
    volumes:
      - ./backend/database:/var/lib/mysql
    ports:
      - 3307:3307
    networks:
      - backend

networks:
  backend:
    driver: bridge
    name: backend